// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAzsIZy5mLsxdWWkMtBTi8EbNCr_TzQ-o',
    appId: '1:242903522636:web:e7ed9dd7aa777a2a5f83e9',
    messagingSenderId: '242903522636',
    projectId: 'mochiroam-ai-4cc7c',
    authDomain: 'mochiroam-ai-4cc7c.firebaseapp.com',
    storageBucket: 'mochiroam-ai-4cc7c.firebasestorage.app',
    measurementId: 'G-RPQNK348EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn71cycZzMxt0tHacmAUAd19iH4X8IGqU',
    appId: '1:242903522636:android:545f9c08eb12989a5f83e9',
    messagingSenderId: '242903522636',
    projectId: 'mochiroam-ai-4cc7c',
    storageBucket: 'mochiroam-ai-4cc7c.firebasestorage.app',
  );
}
